@extends('layouts.app')

@section('title', 'Documents')

@section('content')
<div class="space-y-6">
    <!-- Header -->
    <div class="flex justify-between items-center">
        <div>
            <h2 class="text-2xl font-bold text-gray-900">Generated Documents</h2>
            <p class="text-sm text-gray-600 mt-1">PDF document management</p>
        </div>
        <div class="flex space-x-2" x-data="{ open: false }">
            <div class="relative">
                <button @click="open = !open" class="btn btn-primary">
                    <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
                    </svg>
                    Generate Document
                </button>
                <div x-show="open" @click.away="open = false" x-cloak class="absolute right-0 mt-2 w-56 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-10">
                    <div class="py-1">
                        <a href="{{ route('documents.nota-dinas.generate') }}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                            Nota Dinas Internal
                        </a>
                        <a href="{{ route('documents.bapbj.generate') }}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                            BAPBJ
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Documents Table -->
    <div class="card">
        <div class="card-body p-0">
            @if($documents->count() > 0)
                <div class="overflow-x-auto">
                    <table class="table">
                        <thead class="table-header">
                            <tr>
                                <th class="table-header-cell">Document #</th>
                                <th class="table-header-cell">Type</th>
                                <th class="table-header-cell">Generated By</th>
                                <th class="table-header-cell">Generated At</th>
                                <th class="table-header-cell">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="table-body">
                            @foreach($documents as $document)
                            <tr>
                                <td class="table-cell">
                                    <span class="font-mono font-semibold text-blue-600">{{ $document->document_number }}</span>
                                </td>
                                <td class="table-cell">
                                    @if($document->document_type === 'nota_dinas')
                                        <span class="badge badge-info">Nota Dinas</span>
                                    @elseif($document->document_type === 'bapbj')
                                        <span class="badge badge-success">BAPBJ</span>
                                    @else
                                        <span class="badge badge-secondary">{{ ucfirst($document->document_type) }}</span>
                                    @endif
                                </td>
                                <td class="table-cell">{{ $document->user->username }}</td>
                                <td class="table-cell text-gray-500">{{ $document->created_at->format('M j, Y H:i') }}</td>
                                <td class="table-cell">
                                    <div class="flex items-center space-x-2">
                                        <a href="{{ route('documents.download', $document) }}" class="text-blue-600 hover:text-blue-800" title="Download">
                                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
                                            </svg>
                                        </a>
                                        <form action="{{ route('documents.destroy', $document) }}" method="POST" class="inline" onsubmit="return confirm('Are you sure?')">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="text-red-600 hover:text-red-800" title="Delete">
                                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                                                </svg>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

                @if($documents->hasPages())
                <div class="px-6 py-4 border-t border-gray-200">
                    {{ $documents->links() }}
                </div>
                @endif
            @else
                <div class="p-12 text-center">
                    <svg class="w-16 h-16 mx-auto text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                    <p class="mt-4 text-gray-600">No documents generated yet</p>
                </div>
            @endif
        </div>
    </div>
</div>

<style>
    [x-cloak] { display: none !important; }
</style>
@endsection
